name: flutter_braintree
description: Flutter plugin that wraps the native Braintree SDKs. Enables payments with credit cards, PayPal, Google Pay and more.
version: 4.0.0
homepage: https://github.com/pikaju/flutter-braintree

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_braintree
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
