name: braintree_flutter_plus
description: Enhanced Flutter plugin that wraps the native Braintree SDKs with latest updates. Supports iOS 15+, Android 12+, and includes PayPal vault flow fixes.
version: 5.0.0
homepage: https://github.com/adlyyy4/flutter-braintree
repository: https://github.com/adlyyy4/flutter-braintree
issue_tracker: https://github.com/adlyyy4/flutter-braintree/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.5.0"


dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.braintree_flutter_plus
        pluginClass: FlutterBraintreePlugin
      ios:
        pluginClass: FlutterBraintreePlugin
